//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBHXH.Prototype.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eBHXH.Prototype.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1033\deflangfe1041\themelang1033\themelangfe1041\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}
        ///{\f34\fbidi \froman\fcharset0\fprq2{\*\panose 02040503050406030204}Cambria Math;}{\f52\fbidi \froman\fcharset2\fprq2{\*\panose 05020102010507070707}Wingdings 2;}
        ///{\flomajor\f31500\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _101_PhieuGiaoNhanHoSo {
            get {
                return ResourceManager.GetString("_101_PhieuGiaoNhanHoSo", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap address32x32 {
            get {
                object obj = ResourceManager.GetObject("address32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap agree {
            get {
                object obj = ResourceManager.GetObject("agree", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application {
            get {
                object obj = ResourceManager.GetObject("application", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_view_tile {
            get {
                object obj = ResourceManager.GetObject("application_view_tile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap az64x64 {
            get {
                object obj = ResourceManager.GetObject("az64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BalloonSearch_60_pictureBox1_Image {
            get {
                object obj = ResourceManager.GetObject("BalloonSearch_60_pictureBox1_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon BHXHVN {
            get {
                object obj = ResourceManager.GetObject("BHXHVN", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BHXHVN_32x32 {
            get {
                object obj = ResourceManager.GetObject("BHXHVN_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BHXHVN1 {
            get {
                object obj = ResourceManager.GetObject("BHXHVN1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BHXHVN24x24 {
            get {
                object obj = ResourceManager.GetObject("BHXHVN24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BinhThuong24_24 {
            get {
                object obj = ResourceManager.GetObject("BinhThuong24_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calendar128x128 {
            get {
                object obj = ResourceManager.GetObject("calendar128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap card48x48 {
            get {
                object obj = ResourceManager.GetObject("card48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cate {
            get {
                object obj = ResourceManager.GetObject("cate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap check128x128 {
            get {
                object obj = ResourceManager.GetObject("check128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap checkall128x128 {
            get {
                object obj = ResourceManager.GetObject("checkall128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chidinh48x48 {
            get {
                object obj = ResourceManager.GetObject("chidinh48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clock128x128 {
            get {
                object obj = ResourceManager.GetObject("clock128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap D02_TS {
            get {
                object obj = ResourceManager.GetObject("D02_TS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Document {
            get {
                object obj = ResourceManager.GetObject("Document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Drawing {
            get {
                object obj = ResourceManager.GetObject("Drawing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap excel48x48 {
            get {
                object obj = ResourceManager.GetObject("excel48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap feed {
            get {
                object obj = ResourceManager.GetObject("feed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filter48x48 {
            get {
                object obj = ResourceManager.GetObject("filter48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag64x64 {
            get {
                object obj = ResourceManager.GetObject("flag64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_new {
            get {
                object obj = ResourceManager.GetObject("folder_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_search128x128 {
            get {
                object obj = ResourceManager.GetObject("folder_search128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_updates128x128 {
            get {
                object obj = ResourceManager.GetObject("folder_updates128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Folder2 {
            get {
                object obj = ResourceManager.GetObject("Folder2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Folder3 {
            get {
                object obj = ResourceManager.GetObject("Folder3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Folder4 {
            get {
                object obj = ResourceManager.GetObject("Folder4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderClosed {
            get {
                object obj = ResourceManager.GetObject("FolderClosed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderOpen {
            get {
                object obj = ResourceManager.GetObject("FolderOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap form {
            get {
                object obj = ResourceManager.GetObject("form", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonAlignCenter_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonAlignCenter_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonAlignJustify_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonAlignJustify_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonAlignLeft_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonAlignLeft_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonAlignRight_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonAlignRight_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonCopy_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonCopy_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonCut_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonCut_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonExit_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonExit_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonFileSaveAs_ImageSmall {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonFileSaveAs_ImageSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonFontBold_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonFontBold_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonFontItalic_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonFontItalic_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonFontStrike_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonFontStrike_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonFontUnderline_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonFontUnderline_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonGoto_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonGoto_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonItem2_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonItem2_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonItem20_ImageSmall {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonItem20_ImageSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonItem3_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonItem3_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonItem4_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonItem4_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonItem47_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonItem47_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonItem48_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonItem48_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonItem49_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonItem49_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonItem5_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonItem5_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonItem53_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonItem53_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonItem54_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonItem54_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonItem55_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonItem55_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonItem6_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonItem6_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonItem61_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonItem61_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonItem63_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonItem63_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonItem64_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonItem64_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonItem65_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonItem65_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonItem66_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonItem66_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonItem7_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonItem7_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonNew_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonNew_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonOptions_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonOptions_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonReplace_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonReplace_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonSave_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonSave_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonTextColor_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonTextColor_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_16_buttonUndo_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_16_buttonUndo_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_24_buttonFile_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_24_buttonFile_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_32_buttonFileSaveAs_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_32_buttonFileSaveAs_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_32_buttonFind_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_32_buttonFind_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_32_buttonItem1_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_32_buttonItem1_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_32_buttonItem10_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_32_buttonItem10_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_32_buttonItem11_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_32_buttonItem11_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_32_buttonItem12_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_32_buttonItem12_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_32_buttonItem20_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_32_buttonItem20_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_32_buttonItem21_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_32_buttonItem21_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_32_buttonItem23_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_32_buttonItem23_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_32_buttonItem24_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_32_buttonItem24_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_32_buttonItem25_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_32_buttonItem25_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_32_buttonItem56_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_32_buttonItem56_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_32_buttonItem57_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_32_buttonItem57_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_32_buttonItem58_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_32_buttonItem58_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_32_buttonItem59_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_32_buttonItem59_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_32_buttonItem8_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_32_buttonItem8_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_32_buttonItem9_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_32_buttonItem9_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_32_buttonMargins_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_32_buttonMargins_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_32_buttonPaste_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_32_buttonPaste_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_32_buttonX1_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_32_buttonX1_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_500_ribbonControl1_BackgroundImage {
            get {
                object obj = ResourceManager.GetObject("frmMain_500_ribbonControl1_BackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem18_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem18_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem19_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem19_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem22_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem22_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem30_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem30_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem31_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem31_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem32_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem32_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem33_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem33_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem34_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem34_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem35_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem35_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem36_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem36_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem37_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem37_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem38_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem38_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem39_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem39_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem40_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem40_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem41_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem41_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem42_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem42_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem43_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem43_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem44_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem44_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem45_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem45_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem46_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem46_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem67_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem67_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem68_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem68_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem69_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem69_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem70_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem70_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem71_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem71_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem72_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem72_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem73_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem73_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem74_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem74_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem75_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem75_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem76_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem76_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmMain_64_buttonItem77_Image {
            get {
                object obj = ResourceManager.GetObject("frmMain_64_buttonItem77_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Harddrive {
            get {
                object obj = ResourceManager.GetObject("Harddrive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Home2 {
            get {
                object obj = ResourceManager.GetObject("Home2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Inbox {
            get {
                object obj = ResourceManager.GetObject("Inbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Info_16_Ribbonpad_Info_png {
            get {
                object obj = ResourceManager.GetObject("Info_16_Ribbonpad_Info_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InfoImage {
            get {
                object obj = ResourceManager.GetObject("InfoImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KoHopLe48x48 {
            get {
                object obj = ResourceManager.GetObject("KoHopLe48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mail3 {
            get {
                object obj = ResourceManager.GetObject("Mail3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap move48x48 {
            get {
                object obj = ResourceManager.GetObject("move48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap normal64x64 {
            get {
                object obj = ResourceManager.GetObject("normal64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Outbox {
            get {
                object obj = ResourceManager.GetObject("Outbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pause32x32 {
            get {
                object obj = ResourceManager.GetObject("pause32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Reading_24x24 {
            get {
                object obj = ResourceManager.GetObject("Reading_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reading128x128 {
            get {
                object obj = ResourceManager.GetObject("reading128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap receive64x64 {
            get {
                object obj = ResourceManager.GetObject("receive64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RecycleBin {
            get {
                object obj = ResourceManager.GetObject("RecycleBin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rename48x48 {
            get {
                object obj = ResourceManager.GetObject("rename48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Resources_16_Unpinned {
            get {
                object obj = ResourceManager.GetObject("Resources_16_Unpinned", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Resources_32_Document {
            get {
                object obj = ResourceManager.GetObject("Resources_32_Document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Resources_32_OpenExistingPlace {
            get {
                object obj = ResourceManager.GetObject("Resources_32_OpenExistingPlace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_16x16 {
            get {
                object obj = ResourceManager.GetObject("search_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Single_Window_Example {
            get {
                object obj = ResourceManager.GetObject("Single_Window_Example", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spam {
            get {
                object obj = ResourceManager.GetObject("Spam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sync48x48 {
            get {
                object obj = ResourceManager.GetObject("sync48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text48x48 {
            get {
                object obj = ResourceManager.GetObject("text48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unread48x48 {
            get {
                object obj = ResourceManager.GetObject("unread48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zip {
            get {
                object obj = ResourceManager.GetObject("Zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
